package(default_visibility = ["//visibility:public"])

load("@new_rules_rust//rust:def.bzl", "rust_library")

rust_library(
    name = "hello_macro",
    srcs = ["src/lib.rs"],
    crate_type = "proc-macro"
)